services:
    news-scraper:
        build:
            context: ./
            dockerfile: ./services/Dockerfile
            args:
                MODULE_NAME: news-scraper
                MODULE_ENTRY: news_scraper.main
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - SCRAPE_INTERVAL=60
        restart: unless-stopped

        develop:
            watch:
                - action: rebuild
                  path: ./services/Dockerfile

    # admin:
    #     build:
    #         context: ./
    #         dockerfile: ./services/admin/Dockerfile
    #     environment:
    #         - DATABASE_URL=${DATABASE_URL}
    #     ports:
    #         - "8000:8000"
    #     restart: unless-stopped

    #     develop:
    #         watch:
    #             - action: rebuild
    #               path: ./services/admin/Dockerfile
