services:
    bubbleseek-scraper:
        build:
            context: ./
            dockerfile: ./services/Dockerfile
            args:
                MODULE_NAME: bubbleseek-scraper
                MODULE_ENTRY: bubbleseek_scraper.main
        environment:
            - FA_DATABASE_URL=${FA_DATABASE_URL}
            - FA_BUBBLESEEK_SCRAPER_INTERVAL=60
        restart: unless-stopped

        develop:
            watch:
                - action: rebuild
                  path: ./services/Dockerfile

    macro-scraper:
        build:
            context: ./
            dockerfile: ./services/Dockerfile
            args:
                MODULE_NAME: macro-scraper
                MODULE_ENTRY: macro_scraper.main
        environment:
            - FA_DATABASE_URL=${FA_DATABASE_URL}
            - FA_MACRO_SCRAPER_BASE_URL=${FA_MACRO_SCRAPER_BASE_URL}
            - FA_MACRO_SCRAPER_POLL_INTERVAL=3600
            - FA_MACRO_SCRAPER_HISTORY_DAYS=365
        restart: unless-stopped

        develop:
            watch:
                - action: rebuild
                  path: ./services/Dockerfile

    migrate:
        build:
            context: ./
            dockerfile: ./services/migrate/Dockerfile
        environment:
            - FA_DATABASE_URL=${FA_DATABASE_URL}
        profiles:
            - migrate
