[project]
name = "stock-scraper"
version = "0.1.0"
description = "Polls Stock API and saves to DB"
requires-python = ">=3.11"
dependencies = [
  "aiohttp>=3.9.0",
  "finance-shared",
  "pyyaml>=6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
finance-shared = { workspace = true }
